#config.yaml
hyperparameters:
    cuda: True
    batch_size: 100
    x_dim: 784
    hidden_dim: 400
    latent_dim: 20
    lr: 1e-3
    epochs: 20

paths:
    dataset_path: "~/datasets"
    checkpoint: "trained_model"
    orig_data: "orig_data"
    reconstructions: "reconstructions"
    generated_sample: "generated_sample"
